import 'package:get/get.dart';

class Translate extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'hello': 'Hello',
          'WELCOME TO ENGLISH HUB': 'WELCOME TO ENGLISH HUB',
          'Daily Sentence': 'Daily Sentence',
          'Listening': 'Listening',
          'Reading': 'Reading',
          'Speaking': 'Speaking',
          'Writing': 'Writing',
          'Home': 'Home',
          'Login': 'Login',
          'LOGIN': 'LOGIN',
          'Sign Up': 'Sign Up',
          'REGISTER': 'REGISTER',
          'already have an account': 'Already have an account ?',
          'Don\'t have an account': 'Don\'t have an account ?',
          'FORGOT PASSWORD': 'FORGOT PASSWORD',
          'Log in \nto continue': 'Log in \nto continue',
          'Sign Up \nto continue': 'Sign Up \nto continue',
          'VISITOR': 'VISITOR',
          'WORD LOOKUP': 'Word Lookup',
          'LEARNING RESOURCES': 'Learning Resources',
          'LEARNING PLANS': 'Learning Plans',
          'wordLookupDescription':
              'Provide definitions, pronunciations, example sentences, and video aids for words, supporting various online engines such as Bing, Collins, and Cambridge.',
          'learningResourcesDescription':
              'Access a diverse range of learning materials, from classic literature to English readings and news periodicals, with progress tracking for ebooks. Enhance understanding and listening skills with a variety of video materials, including TV shows, movies, lectures, and educational courses.',
          'learningPlansDescription':
              'Users can customize their daily learning frequency and track progress with the provided word books, adjusting their learning plans as needed.',
          'Ready to start learning': 'Ready to start your journey to a fun and engaging learning experience? Let\'s get started!',
          'Clearhead': 'Clearhead',
          'Let\'s begin': 'Let\'s begin !',
          'Welcome': 'Welcome',
          'welcomeDescription': 'English Hub is a platform that helps you learn English in a fun and interactive way.',
          'Skip': 'Skip',
          'Guest Access': 'Guest Access',
          'Guest': 'Guest',
          'Sign Out': 'Sign Out',
          'Go to Login': 'Go to Login',
          'Day': 'Day',
          'Night': 'Night',
          'Custom Theme': 'Custom Theme',
          'My Voiceover': 'My Voiceover',
          'Hot Voiceover': 'Hot Voiceover',
        },
        'zh_CN': {
          'hello': '你好',
          'WELCOME TO ENGLISH HUB': '欢迎来到英语中心',
          'Daily Sentence': '每日一句',
          'Listening': '听力',
          'Reading': '阅读',
          'Speaking': '口语',
          'Writing': '写作',
          'Home': '首页',
          'Login': '登录',
          'LOGIN': '登录',
          'Sign Up': '注册',
          'REGISTER': '注册',
          'already have an account': '已有账号？',
          'Don\'t have an account': '没有账号？',
          'FORGOT PASSWORD': '忘记密码',
          'Log in \nto continue': '登录\n继续',
          'Sign Up \nto continue': '注册\n继续',
          'VISITOR': '游客',
          'WORD LOOKUP': '单词查询',
          'LEARNING RESOURCES': '学习资源',
          'LEARNING PLANS': '学习计划',
          'wordLookupDescription':
              '提供单词释义、发音、例句以及视频记忆辅助，支持多种在线查询引擎，如必应、柯林斯、剑桥等。',
          'learningResourcesDescription':
              '提供多样化的学习材料，包括经典文学作品、英语读物和新闻外刊等，电子书类材料还可以记录用户的阅读进度。通过各类视频材料，包括美剧、电影片段、演讲和教育课程等，增强语境理解和听力技能。',
          'learningPlansDescription': '用户可以自定义每日学习频率并通过提供的单词书跟踪进度，根据需要调整学习计划。',
          'Ready to start learning': '准备好开始您的学习之旅了吗？让我们开始吧！',
          'Clearhead': '放松清心',
          'Let\'s begin': '让我们开始吧！',
          'Welcome': '欢迎',
          'welcomeDescription': '英语中心是一个帮助您以有趣和互动的方式学习英语的平台。',
          'Skip': '跳过',
          'Guest Access': '游客访问',
          'Guest': '游客',
          'Sign Out': '退出登录',
          'Go to Login': '前往登录',
          'Day': '白天',
          'Night': '夜晚',
          'Custom Theme': '自定义主题',
          'My Voiceover': '我的配音',
          'Hot Voiceover': '热门配音',
        }
      };
}
